apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: app-cicd-test-2
  annotations:
    "backstage.io/project": "png-gcp-learning-poc"
    "backstage.io/cloud-run": "cicd-test-2"
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: monkmantra/app-cicd-test-2
spec:
  type: service
  owner: user:de-ims
  lifecycle: experimental
  dependsOn:
    - component:default/infra-cicd-test-2
  providesApis:
    - cicd-test-2

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: cicd-test-2
  description: The App APIs Specification. 
  tags:
    - fastapi
spec:
  type: openapi
  lifecycle: experimental
  owner: user:de-ims
  definition:
    $text: ./fastapi.yaml
